y<-rtia$Accident_Severity
days<-rtia$Day_of_Week
wdays<-table(days,y)
chisq.test(wdays)
month<-rtia$Month
months<-table(month,y)
chisq.test(months)
year<-rtia$Year
Years<-table(year,y)
chisq.test(Years)
date<-rtia$Date
dates<-table(date,y)
chisq.test(dates)
time<-rtia$Time
time1<-table(time,y)
chisq.test(time1)
mode<-rtia$Mode
modes<-table(mode,y)
chisq.test(modes)
