a<-table(rtia$Day_of_Week,rtia$Accident_Severity)
a<-table(rtia$Day_of_Week,rtia$Accident_Severity=="1")
a1<-table(rtia$Day_of_Week,rtia$Accident_Severity=="2")
a2<-table(rtia$Day_of_Week,rtia$Accident_Severity=="3")
x1<-seq(900,140000,20000)
par(mar=c(5,4,4,5)+.1)
Nonfatal<-c(a[c(8:14)])
plot(x1,Nonfatal,type="l",col="red")
Fatal<-c(a1[c(8:14)])
par(new=TRUE)
plot(x1, Fatal,type="l",col="blue",xaxt="n",yaxt="n",xlab="",ylab="")
Killed<-c(a2[c(8:14)])
par(new=TRUE)
plot(x1,Killed,type="l",col="green",xaxt="n",yaxt="n",xlab="",ylab="")
legend("topleft",col=c("red","blue","green"),lty=1,legend=c("NF","F","K"))
